name: DevSecOps Pipeline Workflow

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout Repository in GH Runner Context
      - name: Set up JDK 17 - Cache Enabled
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout Repository in GH Runner Context
      - name: Set up JDK 17 - Cache Enabled
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: {% raw %} ${{ github.workspace }} {% endraw %} # location for the settings.xml file
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: {% raw %} ${{ github.token }} {% endraw %}

  build-and-push-image:
    name: BnP GHCR
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Log in to the Container registry
        uses: docker/login-action@3d58c274f17dffee475a5520cbe67f0a882c4dbb
        with:
          registry: ghcr.io
          username: {% raw %} ${{ github.actor }} {% endraw %}
          password: {% raw %} ${{ secrets.GITHUB_TOKEN }} {% endraw %}
      - name: Set up JDK 17 - Cache Enabled
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: {% raw %} ${{ github.workspace }} {% endraw %} # location for the settings.xml file
      - name: Generate Executables for Docker Context
        run: mvn clean package
      - name: BnP Docker Image
        run: |
          docker build -t ${{values.containerRegistry}}/${{values.imageProject}}/${{values.imageName}}  .
          docker push ${{values.containerRegistry}}/${{values.imageProject}}/${{values.imageName}}
